version: "3.1"
services:

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    command: ["daemon", "--migrate", "--enable-pubsub-experiment"]

  orbitdb:
    image: orbitdb/orbit-db-http-api:1151
    container_name: orbitdb
    depends_on: 
      - "ipfs"
    restart: always
    ports:
      - 6001:6001
    volumes:
      - .orbitdb:/orbitdb
      - ./orbit_conf.json:/orbit_conf.json
    command: ["node", "src/cli.js", "api", "--orbitdb-dir", "/orbitdb", "--no-https", "--http1", "--api-port", "6001"]
    environment: 
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - ORBITDB_CONF=/orbit_conf.json