version: "3.1"
services:

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - .ipfs_data:/data/ipfs
      
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    entrypoint: []
    command: sh -c "/ipfs/config/start_ipfs daemon --migrate --enable-pubsub-experiment"

  orbitdb:
    image: tearust/tea-orbit-db-http-api:v0.0.4
    container_name: orbitdb
    depends_on: 
      - "ipfs"
    restart: always
    ports:
      - 6001:6001
    env_file: .env
    volumes:
      - ./src:/api/src
      - .orbitdb:/orbitdb
    command: ["node", "src/cli.js", "api", "--orbitdb-dir", "/orbitdb", "--no-https", "--http1", "--api-port", "6001"]
    environment: 
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - SEED=${SEED}
      - ADMIN_LIST=${ADMIN_LIST}
